psb_video: avoid multiple definition of const array [MRFLD-VIDEO].
BZ: 45327

By including tng_VPB.h in many C files, an issue happen on link time
of type :
out/target/product/mrfl_hvp/obj/SHARED_LIBRARIES/pvr_drv_video_intermediates/tng_VP8.o:(.rodata+0x160): multiple definition of `b_mode_prob'
out/target/product/mrfl_hvp/obj/SHARED_LIBRARIES/pvr_drv_video_intermediates/psb_drv_video.o:(.rodata+0x380): first defined here

To avoid such situation, const array is defined as extern and
the initialization is moved to tng_VP8.c

Change-Id: Ia6f086af1c206d34d7a103bae517e8e09104d32c
Signed-off-by: Aymen Zayet <aymen.zayet@intel.com>
Reviewed-on: http://android.intel.com:8080/59709
Reviewed-by: Ding, Haitao <haitao.ding@intel.com>
Tested-by: Ding, Haitao <haitao.ding@intel.com>
Reviewed-by: buildbot <buildbot@intel.com>
Tested-by: buildbot <buildbot@intel.com>